name: Package Plugin

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python 3.8
      uses: actions/setup-python@v2
      with:
        python-version: 3.8

    - name: Install OctoPrint
      run: |
        python -m pip install --upgrade pip
        pip install OctoPrint

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install .

    - name: Package Plugin
      run: |
        python setup.py sdist

    - name: Get the version
      id: get_version
      run: echo ::set-output name=VERSION::$(python setup.py --version)

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        tag_name: ${{ github.ref }}
        release_name: Release ${{ github.ref }}
        draft: false
        prerelease: false

    - name: Upload Release Asset
      id: upload-release-asset 
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }} 
        asset_path: ./dist/${{ steps.get_version.outputs.VERSION }}.tar.gz
        asset_name: OctoprintCheckListDisplayer-${{ steps.get_version.outputs.VERSION }}.tar.gz
        asset_content_type: application/gzip
